# Generated by Django 5.0 on 2024-01-04 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_permissions_role_user_role"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Permissions",
            new_name="Permission",
        ),
    ]
